openshift/baremetal-operator

Makefile
cmd/make-bm-worker/main.go
cmd/make-bm-worker/templates/templates.go
cmd/make-bm-worker/templates/templates_test.go
cmd/make-virt-host/main.go
deploy/crds/demo-hosts.yaml
deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
docs/BaremetalHost_ProvisioningState.dot
docs/api.md
docs/dev-setup.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

pull upstream 20190702

---

Makefile
build/Dockerfile
cmd/manager/main.go
pkg/version/version.go

Adds version information to the logs.

pull upstream 20190703

---

docs/api.md
pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/irmc.go

Add fujitsu iRMC support

---

README.md
docs/api.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

Documentation updates

---

.travis.yml
Makefile
pkg/controller/baremetalhost/baremetalhost_controller_test.go

From https://github.com/metal3-io/baremetal-operator/pull/249

use table driven tests

---

pkg/provisioner/ironic/ironic.go

When the host is in certain provisioning states we cannot change its
power status. Rather than erroring and trying over and over, report
the issue and delay retrying to give the host a chance to move into a
state where power can be changed.
From https://github.com/metal3-io/baremetal-operator/pull/275

improve error handling in power state management code

---

docs/api.md
docs/baremetalhost-states.md
docs/testing.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go

Merge fix in https://github.com/metal3-io/baremetal-operator/pull/278 downstream

fix adoption for steady state hosts

---

Makefile
docs/api.md
docs/dev-setup.md
pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go
pkg/bmc/redfish.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go

Contents:
* metal3-io#282
* metal3-io#283
* metal3-io#291
* metal3-io#300
* metal3-io#288
* metal3-io#284
* metal3-io#305
* metal3-io#301

Merge from upstream

---

pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go
pkg/bmc/redfish.go
pkg/provisioner/ironic/ironic.go

This pulls in the redfish, ilo5, and iDRAC changes for virtual media.

Cherry-pick virtual media changes from metal3-io baremetal-operator

---

cmd/make-bm-worker/main.go
cmd/make-bm-worker/templates/templates.go
deploy/crds/metal3.io_baremetalhosts_crd.yaml
docs/api.md
docs/dev-setup.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go
pkg/bmc/redfish.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go
test/e2e/baremetal_test.go

cherry-picked from https://github.com/metal3-io/baremetal-operator/pull/396

Bug 1799219: Verify CA

---

OWNERS

Add honza and stbenjam to owners

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/dependencies.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/provisioner.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/drivers/urls.go
vendor/modules.txt

From https://github.com/metal3-io/baremetal-operator/pull/574

Check provisioner ready status when applying reconcile logic

---

pkg/controller/baremetalhost/host_state_machine.go
pkg/controller/baremetalhost/host_state_machine_test.go
pkg/provisioner/ironic/ironic.go

Backport from upstream metal3-io#645.

Bug 1879034: Ensure the boot mode is set in ironic before starting inspection

---

Dockerfile.ocp

Downstream dockerfile

---

main.go
pkg/provisioner/empty/empty.go

cherry pick the upstream commit

Bug 1913112: Allow BMC details to be omitted for Hosts in Unmanaged state

---

Dockerfile.ocp

We want to build our images without internet access.

Remove yum install genisoimage from Dockerfile.ocp

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine_test.go
docs/api.md
pkg/bmc/irmc.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/prepare_test.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/raid_test.go
pkg/provisioner/provisioner.go

I will pick up the upstream PRs after that has been merged, and will add that commits into this one. 
URL of upstream PRs are as follows.
- https://github.com/metal3-io/baremetal-operator/pull/908
Therefore, please pend the review of this PR.

Fix RAID feature

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/prepare_test.go

I will pick up the upstream PRs after that has been merged, and will add that commits into this one. 
URL of upstream PRs are as follows.
- https://github.com/metal3-io/baremetal-operator/pull/929
Therefore, please pend the review of this PR.

Bug 1986654: Auto cleaning step in Prepare stage failed

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/preprovisioningimage_controller.go

OCPBUGS-17363: Trigger reconcile on Secret change

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go

(cherry picked from commit 7c1a7cd1707ae37aa09a9d5708a56455e61d554e)

OCPBUGS-20315: Add an explicit Architecture field
