Dockerfile
Move a copy of build/Dockerfile into the root of the repo.  That's
where Dockerfiles reside in most other OpenShift repos.  We also plan
to change this file upstream to not be based on an OpenShift base, so
this copy will remain the one we use in OpenShift.
=> Move Dockerfile to root dir.

Dockerfile
Commit 9384e31977aba0e183d2a5d2646770632e349d20 changed the upstream
Dockerfile (build/Dockerfile) to use "make build".  Do the same for
the OpenShift Dockerfile.
=> Dockerfile: Sync build change from upstream Dockerfile.

cmd/manager/main.go
This patch configures a prometheus metrics endpoint for the
baremetal-operator.  The metrics endpoint only listens on localhost by
default, but this can be configured through a command line argument.
This can be tested with `make run` and then run the following command:
$ curl http://localhost:8080/metrics
Closes #245
=> Configure metrics endpoint.

pkg/apis/metal3/v1alpha1/baremetalhost_types.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/ironic_test.go
This introduces handling of the gophercloud's Firmware
ExtraHardwareDataSection.  Today, this only includes known
BIOS fields.  If we are able to determine all likely data
potentially within the Firmware section we can expand the
data and fields handled.
Resolves: #220
=> Persist firmware and bios data during introspection.

deploy/operator_ironic.yaml
I don't think this file is being used but we
should probably reference the current names.
=> Reference the current ironic images

cmd/manager/main.go
In the OpenShift integrated case this conflicts with coredns which binds
to :::8080, switching to 8085 should avoid this conflict with the
default.
Fixes: #252
=> Avoid port conflict for metrics endpoint

Gopkg.lock, Gopkg.toml, vendor/github.com/gophercloud/gophercloud/acceptance/openstack/compute/v2/compute.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/results.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/testing/fixtures.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/testing/fixtures.go
This change pulls includes:
- Improvement: return versions supported by the API
- Bug fix: Reformat Args in CleanStep from `map[string]string` to `map[string]interface{}`
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Update to latest gophercloud revision

pkg/apis/metal3/v1alpha1/baremetalhost_types.go, pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go, pkg/provisioner/ironic/ironic.go
Using the presence of a consumerRef value to indicate that a host is
in use means we have a race condition when a host is first registered
if the machine controller grabs the host and allocates it to a
machine before the host has finished inspection. To avoid the race,
use the WasProvisioned() function to test whether a host has actually
been provisioned instead of looking only at the consumer reference.
This update requires changing the expected behavior in an existing
unit test (because it was wrong) and adding a new unit test for the
new case.
=> only skip inspection for fully provisioned hosts

Makefile, cmd/make-virt-host/main.go, pkg/provisioner/ironic/ironic.go
This enables gosec to run as part of the lint target, therefore running
it as well as part of CI.
This also adds the needed command to install it as part of the CI run.
=> Run gosec with lint target

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go
Instead of logging all of the ironic settings every time the
reconciler builds a provisioner, log them once on startup.
We don't use the init() function for this because logging isn't
configured yet by the time that is called.
From https://github.com/metal3-io/baremetal-operator/pull/274
=> move ironic settings logging to startup function

pkg/bmc/access.go, pkg/bmc/idrac.go, pkg/bmc/ipmi.go, pkg/bmc/irmc.go
Instead of hard-coding the creation of the AccessDetails structs in one function, register the factories for making different types and associate them with the values that show up in the URL scheme field to select them.
Merging https://github.com/openshift/baremetal-operator/pull/39
=> make access details more dynamic

.travis.yml, Makefile
This syncs the makefile with upstream so golint is installed as well as
gosec automatically if needed.
Related to https://github.com/metal3-io/baremetal-operator/pull/311
=> Install golint in Makefile if needed

pkg/bmc/access.go, pkg/bmc/access_test.go, pkg/bmc/idrac.go, pkg/bmc/ipmi.go, pkg/bmc/irmc.go, pkg/bmc/redfish.go, pkg/provisioner/ironic/ironic.go
This cherry-picks the features that enable management of virtual media for Redfish, iLO5, and iDRAC to OpenShift 4.3 release branch of baremetal-operator.
=> Bug 1781833: Cherry-pick virtual media changes to 4.3

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/ironic_test.go
This can be one of two keys, depending on whether the host
got an ipv4 or ipv6 address, so use the ipv6 key in the case
where the ipv4 one is unset.
Currently in a single-stack ipv6 deployment the IP ends up
empty like:
Hostname:     worker-0.ostest.test.metalkube.org
Nics:
Ip:
But with this change Ip should be correctly populated.
Cherry-Pick of https://github.com/metal3-io/baremetal-operator/pull/457
=> Bug 1807854 : Don't assume IPv4 in introspection data

docs/api.md, pkg/hardware/profile.go
This is a cherry pick of PR# 486 upstream
OCP Baremetal IPI inside of Openstack environment requires the RootDeviceHint to be /dev/vdb when a pxeboot is performed given that OSP uses nova rescue and a pxeboot.img as /dev/vda.
=> Bug 1826418: Add openstack profile to BMO

Makefile
Similar to #60 -- we need to use `-mod=vedor` when building tools.
Downstream jobs can't access the internet at build time, and therefore
we're vendoring all Go dependencies. In order to actually build the
binary without attempting to download modules from the internet, we have
to set the -mod flag to vendor.
According to the go build documentation:
"To build using the main module's top-level vendor directory to satisfy
dependencies (disabling use of the usual network sources and local
caches), use 'go build -mod=vendor'."
=> Bug 1838570: Use -mod=vendor when building tools

cmd/get-hardware-details/main.go, pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
Backport fixes from metal3-io#546 to OCP 4.6
=> Bug 1843950: remove infinite reconcile loop when fetching status annotation

cmd/get-hardware-details/main.go, pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
Backport fixes from https://github.com/metal3-io/baremetal-operator/pull/546 to OCP 4.5
=> [release-4.5] Bug 1844205: remove infinite reconcile loop when fetching status annotation

Makefile, build/Dockerfile, docs/deploying.md, go.mod, hack/Dockerfile.golint, hack/Dockerfile.operator-sdk, pkg/provisioner/ironic/ironic.go, vendor/modules.txt
There are a couple of commits on top of the merge:
* Updating the vendor directory to work with golang 1.14 (automatic change)
* Removing the `-mod=vendor` flag from the build command
This solves the same problem as #76 but it's more elegant. Golang 1.14 introduces new defaults that make the `mod` flag unnecessary in our scenario (both upstream and downstream).
=> Merge upstream 2020-06-17

pkg/apis/metal3/v1alpha1/baremetalhost_types.go, pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
Backport of #68 to release-4.4, so so we can populate masters' IP information to make the node/machine link.
=> [release-4.4] Bug 1843230: Read BMH status from annotation

pkg/bmc/access.go, pkg/bmc/access_test.go, pkg/bmc/ibmc.go, pkg/bmc/idrac.go, pkg/bmc/ipmi.go, pkg/bmc/irmc.go, pkg/bmc/redfish.go
All of the redfish BMC's should support `+http` or `+https` explicitly,
however it's not configured for any of the virtualmedia BMC's. This
refactories the registerFactory code to allow specifying schemes for a
BMC, and ensuring the schemed versions exist for every one.
This keeps it explicit, so we can say which BMC's support specifying a
scheme.
Cherry-pick of https://github.com/metal3-io/baremetal-operator/pull/567
=> pkg/bmc: refactor to support all schemes

cmd/make-bm-worker/templates/templates.go, cmd/make-bm-worker/templates/templates_test.go, cmd/make-virt-host/main.go, docs/api.md, docs/baremetalhost-states.md, pkg/apis/metal3/v1alpha1/baremetalhost_types.go, pkg/bmc/redfish.go, pkg/provisioner/ironic/errors.go, pkg/provisioner/ironic/ironic.go
We primarily want b048633 to get the Unmanaged state definition, but this also includes an alias for iLo Redfish support and the change to use a soft power-off before the hard power-off, if possible.
=> Merge upstream 2020-07-10

deploy/crds/metal3.io_baremetalhosts_crd.yaml, pkg/apis/metal3/v1alpha1/baremetalhost_types.go
This PR extends the API to include the new field described in
https://github.com/metal3-io/metal3-docs/blob/master/design/baremetal-operator/implicit-boot-mode.md
without using it, so we can update the cluster API providers to avoid
overwriting the user-provided value when provisioning a host.
=> add explicit boot mode field to baremetal host

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
This PR includes a few changes to behavior for syncing hosts that are paused or that have errors. It also includes a change to not update a host when the power state matches the desired state, so that the host is not constantly being reconciled twice per minute.
=> Sync downstream 20200716

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
Writing a status annotation as well as the Status subresource could cause hot reconcile loops. It's not needed in any case in OpenShift, and has been removed from the baremetal-operator upstream as well.
=> Bug 1851531: Do not write status annotation

pkg/provisioner/ironic/ironic.go
When we go to delete a node we look it up by either the UUID stored in
the Host or by name, but previously when we deleted it from Ironic we
only used the UUID from the Host. This meant if the Host UUID was empty
or didn't match, we would be stuck in a loop from which we could never
recover. We can't have it both ways; either a node found by name is the
one that matches and we should delete it, or it isn't and we should
report that the node cannot be found and thus the delete is complete.
It is not clear under what circumstances we end up in this state. It is
possible that it involves the node being discovered by Ironic before the
Host is created and then immediately deleted.
Treat a host matching by name as the one we are looking for, and delete
it regardless of whether we had already …
=> Bug 1875558: Always delete found host from Ironic on deletion

pkg/controller/baremetalhost/host_state_machine.go
In future we will rename StateReady to StateAvailable, but for now make
sure we correctly handle a Host with StateAvailable so that resources
modified by a future release continue to operate as expected after a
downgrade.
Upstream:  metal3-io#636
=> Bug 1879284: Handle StateAvailable when we see it

Dockerfile
Updating ose-baremetal-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-baremetal-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating ose-baremetal-operator builder & base images to be consistent with ART

pkg/provisioner/ironic/ironic.go
When we go to delete a node we look it up by either the UUID stored in
the Host or by name, but previously when we deleted it from Ironic we
only used the UUID from the Host. This meant if the Host UUID was empty
or didn't match, we would be stuck in a loop from which we could never
recover. We can't have it both ways; either a node found by name is the
one that matches and we should delete it, or it isn't and we should
report that the node cannot be found and thus the delete is complete.
It is not clear under what circumstances we end up in this state. It is
possible that it involves the node being discovered by Ironic before the
Host is created and then immediately deleted.
Treat a host matching by name as the one we are looking for, and delete
it regardless of whether we had already …
=> Bug 1874599: Always delete found host from Ironic on deletion

apis/metal3.io/v1alpha1/baremetalhost_types.go, config/crd/bases/metal3.io_baremetalhosts.yaml, config/render/capm3.yaml, pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go, pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
This is a cherry-pick of https://github.com/metal3-io/baremetal-operator/pull/758
Currently we assume only an ipv4 or an ipv6 IP exists in the
inspection data, but it's valid for both to exist in a dual-stack
scenario.
To avoid changing the BMH API, in this case we create an additional
nic entry in the list, which will contain each IP but otherwise
the same data.
=> Bug 1912701: Handle dual-stack configuration in inspection data

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provision_test.go, pkg/provisioner/ironic/result.go
This is meant to supersede #121. It adds the commit `Ironic: Add result functions` without which it cannot be built.
=> Bug 1917484: Don't adopt after clean failure during deprovisioning

config/crd/ocp/ocp_kustomization.yaml
* Add a new kustomization file that adds the OpenShift annotations
* Only on the OpenShift platform, use this file to generate the BMH CRD
* Copy this generated CRD to the /manifests directory so that the CVO can install it 
This fix is being added so that the BMH CRD does not have to be manually kept in sync with the BMO CRD.
=> Generate BMH CRD with annotations needed for OpenShift

Dockerfile.ocp
Use the OpenShift specific kustomization.yaml to generate the BMH CRD and copy that to the /manifests directory with a name that CVO understands. A run level of 30 ensures that this CRD is installed before CVO manifests are installed at run level 31.
=> Copy generated BMH CRD to /manifests directory for CVO to install it

pkg/bmc/access_test.go, pkg/bmc/ibmc.go, pkg/bmc/idrac.go, pkg/bmc/ilo4.go, pkg/bmc/ipmi.go, pkg/bmc/redfish.go, pkg/bmc/redfish_virtualmedia.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/testbmc/testbmc.go
Instead of using `""` we will be using `no-raid`.
The support for RAID was considering  RAIDInterface defaul value as `""`
to generate the clean steps, this is causing errors in vmedia
deployments with idrac because it uses `no-raid`:
"Node failed to start the first cleaning step. Error: node does not support
this clean step: {'interface': 'raid', 'step': 'delete_configuration'}"
=> Bug 1941636 - BM worker nodes deployment with virtual media failed while trying to clean raid

pkg/bmc/irmc.go
Modify the value of power_interface so that soft power off can be used directly.
When irmc power interface is used, Soft Reboot (Graceful Reset) and Soft Power Off (Graceful Power Off)
are only available if ServerView agents are installed.
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
(cherry picked from commit fa38361162644c43fcab7016b69d84aaa4dac9fe)
=> Bug 1949898: modify power_interface for irmc

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/update_opts.go, pkg/provisioner/ironic/updateopts_test.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
Don't write image data changes to the ironic Node when the latest data is already present.
This is a partial backport of metal3-io#852.
=> Bug 1951671: Lazily update Node image options in Ironic

Dockerfile.ocp
The manifest presented to CVO should contain just the BMH CRD and not other manifests defined in capm3.yaml.
=> Bug 1956607: Fix resources added to 0000_30_baremetal-operator_01_baremetalhost.crd.yaml

config/rbac/auth_proxy_client_clusterrole.yaml, config/render/capm3.yaml
This would allow CVO to drop rbacv1beta1 handling code
=> Bug 1960554: config: use rbacv1 instead of rbacv1beta1

pkg/bmc/irmc.go, pkg/provisioner/ironic/prepare_test.go
This is a downstream version of https://github.com/metal3-io/baremetal-operator/pull/911
Signed-off-by: Zou Yu zouy.fnst@cn.fujitsu.com
In view of the need for further discussion on [#908,](https://github.com/metal3-io/baremetal-operator/pull/908) we can first disable RAID settings for iRMC to avoid clean fail on iRMC servers that do not support hardware RAID.
=> Bug 1969487: Disable raid feature for iRMC server

pkg/bmc/idrac.go, pkg/bmc/ilo5.go, pkg/provisioner/ironic/prepare_test.go
RAID support was disabled for the iRMC driver in #152, but per [discussion](https://github.com/openshift/baremetal-operator/pull/150/#issuecomment-858193623) we're not feeling confident about supporting RAID at all in 4.8, and there's every reason to think the known bug could affect other drivers. Therefore, disable RAID for everything until we're confident enough to want to support it.
=> Bug 1969487: Disable RAID for all drivers

controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go
During provisioning, we want an error to cause the Host to be
deprovisioned again, but we very much do not want that to happen when
the Host is already provisioned. Due to an error in
0a7713bd3b4ff30aef2dac17c2d62a79bfe02872, provisioned Hosts were being
automatically deprovisioned whenever an error (other than a registration
error) occurred.
In practice this only manifested on Adopt() failures, since we don't yet
report power management failures.
(cherry picked from metal3-io#916)
=> Bug 1972374: Don't deprovision provisioned host due to error

controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go
During provisioning, we want an error to cause the Host to be
deprovisioned again, but we very much do not want that to happen when
the Host is already provisioned. Due to an error in
0a7713bd3b4ff30aef2dac17c2d62a79bfe02872, provisioned Hosts were being
automatically deprovisioned whenever an error (other than a registration
error) occurred.
In practice this only manifested on Adopt() failures, since we don't yet
report power management failures.
(cherry picked from metal3-io#916)
=> [release-4.8] Bug 1972426: Don't deprovision provisioned host due to error

controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go
During provisioning, we want an error to cause the Host to be
deprovisioned again, but we very much do not want that to happen when
the Host is already provisioned. Due to an error in
0a7713bd3b4ff30aef2dac17c2d62a79bfe02872, provisioned Hosts were being
automatically deprovisioned whenever an error (other than a registration
error) occurred.
In practice this only manifested on Adopt() failures, since we don't yet
report power management failures.
(cherry picked from metal3-io#916)
=> [release-4.7] Bug 1972430: Don't deprovision provisioned host due to error

Dockerfile.ocp
We build the baremetal-operator binary directly instead of using the
full Makefile target.  This should speed up the build by not
regenerating manifests, and by not building linting tools needlessly.
This also the way it's done upstream.
=> Simplify build in Dockerfile.ocp

pkg/provisioner/ironic/raid.go, pkg/provisioner/ironic/raid_test.go
I will pick up the upstream PRs after that has been merged, and will add that commits into this one. 
URL of upstream PRs are as follows.
- https://github.com/metal3-io/baremetal-operator/pull/942
Therefore, please pend the review of this PR.
=> Bug 1986656: Fix missing case of BuildRAIDCleanSteps

go.mod, go.sum, pkg/bmc/access.go, pkg/bmc/access_test.go, pkg/bmc/ibmc.go, pkg/bmc/idrac.go, pkg/bmc/idrac_virtualmedia.go, pkg/bmc/ilo4.go, pkg/bmc/ilo5.go, pkg/bmc/ipmi.go, pkg/bmc/irmc.go, pkg/bmc/redfish.go, pkg/bmc/redfish_virtualmedia.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/prepare_test.go, pkg/provisioner/ironic/testbmc/testbmc.go, vendor/github.com/gophercloud/gophercloud/.zuul.yaml, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/results.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/urls.go, vendor/github.com/gophercloud/gophercloud/provider_client.go, vendor/modules.txt
Ironic sets the bios_interface by default for all drivers. For some drivers - particularly idrac-virtualmedia, the default should be overridden. If not explicitly set, Ironic will use the default.
This requires an upgrade to a Gophercloud release that supports BIOSInterface.
=> Bug 1928816: Explicitly set node bios_interface

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/update_opts.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
When using format: live-iso, two distinct use-cases exist:
- Boot an installer ISO (non-persistent one-time boot desired)
- Boot an ISO appliance (persistent live-iso boot desired).
The original plan was to solve the installer-iso boot order via
uefibootmgr (running from the live-iso), but this doesn't work
reliably on all hardware.
So expose a variable to control this behavior - in future we may
want to consider a per-BMH variable, but for now expose a
per-BMO variable.
(cherry picked from commit 40fffc5094842631e180296533648c1b6bd59afd)
Conflicts:
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/update_opts.go
=> Bug 2000442: Add LIVE_ISO_FORCE_PERSISTENT_BOOT_DEVICE variable

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/power_test.go
Fix a regression in metal3-io#841 that caused ironic drivers that don't support soft power off (such as Fujitsu when the agent is not available) to fail in an infinite loop instead of falling back to a hard power off.
=> [release-4.9] Bug 2009850: Fix fallback for ironic drivers that don't support soft power off

pkg/provisioner/ironic/update_opts.go, pkg/provisioner/ironic/updateopts_test.go
Since b8dba2c016befacf2ff65004a2ff73008d5ab63a we use the nodeUpdater
with its built-in logging to update the ironic node when the credentials
change. This inadvertantly meant the BMC credentials will be logged in
this case (which is very rare; credentials don't often change).
To prevent this, sanitise new values as they are being logged. Ironic
does not return existing values for passwords, so there is no danger of
them being logged through that route. Currently password fields are only
redacted if they are set as part of a map; in practice this will be safe
for the foreseeable future as the bmc credentials are always set through
a map returned from the driver and not individually.
(cherry picked from commit a08d0b65aa026bb3f2bce4b6e6edcfe70b16e70e)
=> [release-4.9] Bug 2009849: Avoid logging BMC password when creds change

controllers/metal3.io/hostfirmwaresettings_controller.go
Publish events for all invalid settings, not just the first one found.
=> Bug 2035882: Publish events for all invalid HostFirmwareSettings

controllers/metal3.io/hostfirmwaresettings_controller.go, controllers/metal3.io/hostfirmwaresettings_test.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provision_test.go
For these types the value in clean steps should be stored as an integer,
otherwise vendors reject the Redfish request.
(cherry picked from commit b00f767db493eefdb513c345b231965cfdb90203)
=> Bug 2036006: Use integer value in clean steps for HostFirmwareSettings Integer type

pkg/hardwareutils/bmc/access_test.go, pkg/hardwareutils/bmc/irmc.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
Fixed iRMC server deployment failure during IPI.
See openshift/installer#5504 for details.
Signed-off-by: Zou Yu <zouy.fnst@fujitsu.com>
=> Bug 2041765: irmc: change BootInterface to ipxe

apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
PR #201 included a fix which isn't live because we haven't re-vendored the `api` module. This patch fixes it.
=> Bug 2044496: Update vendor

Dockerfile.ocp
Remove `amd64` from go binary builds, this breaks arm64 builds.
https://issues.redhat.com/browse/ARMOCP-324
upstream: https://github.com/metal3-io/baremetal-operator/pull/1097
=> Enable multi-arch builds

Dockerfile.ocp
We move the baremetalhost crd to level 31 where the rest of the CBO
manifests reside.  We set it at 00 to ensure it's installed first as per
the initial intention.
This patch ensures that all CBO manifests are collected into a single
task node during updates.
=> Move bmh crd to level 31

pkg/hardwareutils/bmc/idrac_virtualmedia.go, pkg/hardwareutils/bmc/redfish.go
It was disabled for all drivers in e2d5a7591c5abf751331a0e111e29f1b519c0e11,
but appeared in recent upstream changes for iDRAC-Redfish.
=> [OCP] Disable iDRAC RAID

controllers/metal3.io/host_config_data.go
Report that NetworkData isn't available and return a
blank string id the sectret is present but doesn't contain
the expected key. This is the same as the behaviour when the
secret isn't present at all.
=> Bug 2092650: Stop treating missing network as fatal error

controllers/metal3.io/host_state_machine.go
Calling `registerHost()` in the Inspecting or Preparing states will require that we have a PreprovisioningImage built before we proceed.
machine-image-customization-controller does not reconcile images with the an InfraEnv label for ZTP. Versions > RHACM 2.4 supply a separate controller that reconciles these resources, but earlier versions do not. Earlier versions also disable inspection and do not use any of the features of the Preparing state, so it is safe to simply avoid calling `registerHost()` in these states for these hosts.
=> Bug 2087213: Don't require PreprovisioningImages for older ZTP

pkg/provisioner/ironic/ironic.go
The live-iso provisioning method does not require IPA to be booted on
the server, so don't fail if there is no PreprovisioningImage available.
(cherry picked from commit 8577aac3928b4d86e04414bbe976d0e51d961cf1)
=> Bug 2087213: Don't require pre-provisioning image for live ISO provisioning

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/baremetalhost_controller_test.go, controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go, controllers/metal3.io/hostfirmwaresettings_controller.go, controllers/metal3.io/hostfirmwaresettings_test.go, pkg/provisioner/demo/demo.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/prepare_test.go, pkg/provisioner/provisioner.go
Currently if the host is in the Available state and the HFS settings are
changed it doesn't transition to the Preparing state as it would when the
BareMetalHost settings are changed. This change fixes that.
(cherry picked from commit cd3340b20de240feb1566432def9fc6b678f7626)
=> Bug 2047930: Move from Available to Preparing if HostFirmwareSettings changed

docs/configuration.md, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provisioncapacity_test.go
The limit was designed to avoid glitches when too many hosts DHCP or
boot from PXE. Virtual media requires neither, and with a pre-built ISO
is actually quite efficient.
(cherry picked from commit 57a4af322b20f2abce37cfeedcd8158e071f2863)
=> OCPBUGS-2210: Exclude hosts with virtual media from PROVISIONING_LIMIT

controllers/metal3.io/hostfirmwaresettings_controller.go, controllers/metal3.io/hostfirmwaresettings_test.go
Only update the HFS status if the settings from Ironic have changed or if the conditions were updated.
Currently the reconciler can run an additional time because the Status is updated on each pass.
(cherry picked from commit fad958b6ae284444d59947c4be38e88d153d2d6d)
=> Bug 2061794: [4.10] Only update the HFS status on changes

apis/metal3.io/v1alpha1/baremetalhost_validation.go, apis/metal3.io/v1alpha1/baremetalhost_validation_test.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
This validation is blocking pxe booting when live-iso image format is used along with non-virtualmedia drivers.
Cherry picks e257729ed8d2eff2c62e5591bc2e515c1ed93489
=> OCPBUGS-11310: Revert live-iso validation

pkg/provisioner/ironic/ironic.go
For some reason, BMO creates nodes without the namespace~ prefix, then
updates them. This may cause conflicts between nodes belong to hosts
from different namespaces.
(cherry picked from commit bca45815ea101c99669a8552411cc7b827f5bbaa)
=> OCPBUGS-11870: Create nodes with namespace already prepended

ironic-deployment/components/basic-auth/auth.yaml, ironic-deployment/components/basic-auth/kustomization.yaml, ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
(cherry picked from commit https://github.com/openshift/baremetal-operator/commit/a58a905cccd69284e13eda3db4da07ef2c707aad)
=> OCPBUGS-12828: [release 4.13] Store htpasswd files in Secrets instead of ConfigMaps

apis/metal3.io/v1alpha1/baremetalhost_types.go, config/crd/bases/metal3.io_baremetalhosts.yaml, config/render/capm3.yaml, pkg/provisioner/ironic/devicehints/devicehints.go, pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
Allow a `/dev/disk/by-path/*` path to be specified in root device hints. Also, use this path in inspection results to ensure that paths are stable across reboots, since with the RHEL 9 kernel the actual kernel device filenames are much less stable than they were in RHEL 8.
=> [release-4.13] OCPBUGS-13082: Allow by-path devices in root device hints

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go
This is backport of the fix for issue [OCPBUGS-7581](https://issues.redhat.com/browse/OCPBUGS-7581)
Cherry picks commits from [here](https://github.com/openshift/baremetal-operator/pull/280/commits)
=> OCPBUGS-13927: Deleting unmanaged BMH get stuck fix

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
Currently, if e.g. the deploy ISO has changed, BMO will try to update
the node. Such updates cannot work in most transient states, causing
the reconciler to return early with an error.
(cherry picked from commit 65bf31df7f9289d88c56d15bc87962d3b42fae69)
=> OCPBUGS-13374: Do not try to update images for nodes in transient states

Dockerfile.ocp, Makefile
When we build the image, the code has already been through code review, and CI. Everything has been generated, and linted, and addressed. At the build stage, we just want to compile the binary.
Furthermore, the golangci-lint program seems to require attention every time we upgrade Go in the builder. This breaks the build, and we have to do emergency upgrades to get it unstuck.
Lastly, we use the Makefile target `manager` instead of the low-level Go command.  This gives us build-time information in the binary.
=> Stop linting when building the image

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/preprovisioningimage_controller.go
The default meaning of the Owns() method in the controller-runtime controller is to only trigger reconciles on owner references where we have the 'controller' flag set.
We have never set the 'controller' flag on the networkData Secret used in both the BareMetalHost and PreprovisioningImage controllers.
Since 8550d61f4355f6537b1fc1cd8c480d2ff493e9e9 we no longer set the 'controller' flag on our owner references for Secrets either, in order to allow the same BMC Secret to be shared amongst multiple hosts.
In each of these case we were either never or no longer triggering a reconcile when the Secret changed. Use the equivalent Watch() method call without the IsController option set in the handler to ensure that we still trigger a reconcile even when the 'controller' flag is not set in the …
=> [release-4.13] OCPBUGS-17365: Trigger reconcile on Secret change

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
Doing so may interfere with cleaning. Updates to deploy_interface will
be rejected by Ironic, causing BMO to enter infinite reconcile retries.
(cherry picked from commit e6179d7866b7cc210371f65e12ffade7ffc30dd8)
=> OCPBUGS-21777: Do not update instance_info and deploy_interface for active nodes

pkg/provisioner/ironic/factory.go, pkg/provisioner/ironic/factory_test.go
Relies on another CBO change to provide the required component of
the external URL.
=> OCPBUGS-23504: hack for deploying V6-only clusters from dualstack hubs

apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go, apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go, apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo5.go, apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go, pkg/hardwareutils/bmc/idrac.go, pkg/hardwareutils/bmc/idrac_virtualmedia.go, pkg/hardwareutils/bmc/ilo5.go, pkg/hardwareutils/bmc/redfish.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/ilo5.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
Re-enable RAID interfaces which were previously disabled only in OpenShift BMO (downstream), to be able to support RAID configuration using OpenShift BMO. 
This change reverts:
- https://github.com/openshift/baremetal-operator/commit/e2d5a7591c5abf751331a0e111e29f1b519c0e11
- https://github.com/openshift/baremetal-operator/commit/2b6f680e8c812a0016301e4dfb03fb9c9bdb58da
=> METAL-376: Re-enable RAID interfaces

main.go
Structured logging tools expect a POSIX timestamp. 0a887a16fb26dd26a2b372953ec8d860a3a251b5 reverted to changing the timestamp formatting only in development log mode, after 9ecf1718dfe3f785e151b6d2b5a01ba04e0a00a9 had explicitly and unconditionally set the format to ISO-8601.
However, almost immediately after this,
5bf044038b17aec6c2265d325046f475bc4bb52f bumped the controller-runtime version from 0.13.1 to 0.14.5. In 0.14, the default zap options in controller-runtime changed to RFC3339 - which is the same as ISO-8601 but even worse because subsecond precision (which can be very important to debugging) is lost as well.
This change explicitly restores the original default.
(cherry picked from commit 4b8c5812fbac4fe1b7903e790f02eecfc275e196)
=> [release-4.14] OCPBUGS-24409: Don't munge timestamp in structured logs, again

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
Doing so may interfere with cleaning. Updates to deploy_interface will be rejected by Ironic, causing BMO to enter infinite reconcile retries.
(cherry picked from commit e6179d7866b7cc210371f65e12ffade7ffc30dd8) (cherry picked from commit 4adb8f05f5c313c5ce38f7a8196fce9dfabd2d7f)
=> [release-4.13] OCPBUGS-30629: Do not update instance_info and deploy_interface for active nodes

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
Doing so may interfere with cleaning. Updates to deploy_interface will be rejected by Ironic, causing BMO to enter infinite reconcile retries.
(cherry picked from commit e6179d7866b7cc210371f65e12ffade7ffc30dd8) (cherry picked from commit 4adb8f05f5c313c5ce38f7a8196fce9dfabd2d7f) (cherry picked from commit daf234b418f5299c6c1b3d52d3e0615191582b7d)
=> OCPBUGS-30630: Do not update instance_info and deploy_interface for active nodes

.github/workflows/build-images-action.yml, apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go, config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml, config/render/capm3.yaml, controllers/metal3.io/hostfirmwarecomponents_controller.go, controllers/metal3.io/hostfirmwarecomponents_test.go, go.mod, go.sum, pkg/provisioner/ironic/delete_test.go, pkg/provisioner/ironic/inspecthardware_test.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/power_test.go, pkg/provisioner/ironic/updatehardwarestate_test.go, pkg/provisioner/ironic/validatemanagementaccess_test.go, pkg/provisioner/provisioner.go, vendor/github.com/gophercloud/gophercloud/v2/errors.go, vendor/github.com/gophercloud/gophercloud/v2/openstack/baremetal/v1/nodes/requests.go, vendor/github.com/gophercloud/gophercloud/v2/openstack/baremetal/v1/nodes/results.go, vendor/github.com/gophercloud/gophercloud/v2/provider_client.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go, vendor/github.com/onsi/gomega/CHANGELOG.md, vendor/github.com/onsi/gomega/gomega_dsl.go, vendor/github.com/onsi/gomega/matchers.go, vendor/github.com/onsi/gomega/matchers/receive_matcher.go, vendor/modules.txt
$ git fetch upstream
$ git fetch downstream
$ git checkout -b new-sync-downstream dowstream/master
$ git merge upstream/main
```
[iurygregory@blacklotus baremetal-operator]$ git merge upstream/main 
Auto-merging config/render/capm3.yaml
Merge made by the 'ort' strategy.
.github/workflows/build-images-action.yml                    |  10 ++++++
apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go      |   3 +-
config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml |   3 --
config/render/capm3.yaml                                     |   3 --
controllers/metal3.io/hostfirmwarecomponents_controller.go   |  54 ++++++++++---------------------
controllers/metal3.io/hostfirmwarecomponents_test.go         |   5 +--
go.mod                                                       |   4 +-- …
```
=> NO-ISSUE: Sync upstream April 29

main.go
This is handled in CBO now, so there is no need to carry a downstream patch:
https://github.com/openshift/cluster-baremetal-operator/blob/release-4.15/provisioning/bmo_pod.go#L180-L186
This reverts commit 414dd1f8a6eaa338da91ff30ac8e35d9807c6cce.
=> NO-ISSUE: Revert "downstream-only: Disable webhooks"

apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go, controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/host_state_machine.go, controllers/metal3.io/hostfirmwarecomponents_controller.go, controllers/metal3.io/hostfirmwarecomponents_test.go, main.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provision_test.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
Currently any changes in HostFirmwareComponents won't trigger the firmware update on it.
This commit aims to fix the issues we have observed while testing with real hardware:
- BMH stuck in preparing and executing the same firmware update multiple times
- not being able to define the HostFirmwareComponent manually and have the update applied when the BMH is in preparing.
Signed-off-by: Iury Gregory Melo Ferreira <imelofer@redhat.com>
(cherry picked from commit dc50efe72715358de76de729f61c11b12329625f)
=> OCPBUGS-36673: [4.16] Firmware Update causes BMH to get stuck in Preparing

apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go, pkg/hardwareutils/bmc/redfish.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go
* to fix adding node to ironic error: "Could not find the following interface in the 'ironic.hardware.interfaces.management' entrypoint: ipxe."
Signed-off-by: Dmitri Fedotov <dmitri.fedotov@sap.com>
(cherry picked from commit c73a43ac446bd3f3d0c03a86fe153b325f18fd71)
=> OCPBUGS-37262: fix(redfish): set correct idrac-redfish management interface

controllers/metal3.io/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
At the end of a normal (not live ISO) deployment, Ironic issues
a command to the agent to power off the machine from inside. This
feature avoids relying on often buggy soft power off features of BMCs
(especially IPMI-based), but is not compatible with the way FakeFish [1]
works in case of NC-SI hardware. Such hardware cannot be powered off
because doing so also removes network access to the BMC. FakeFish can
intercept any power calls but cannot intercept the agent API.
This OpenShift-only change adds a new annotation
baremetal.openshift.io/disable-agent-power-off which, if set to "true",
makes BMO configure the Ironic node with the "deploy_forces_oob_reboot"
DriverInfo flag. This flag prevents Ironic from issuing the in-band
power off request.
[1] …
=> OCPBUGS-38404: [OCP] Ability to disable agent power off after deployment

controllers/metal3.io/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
At the end of a normal (not live ISO) deployment, Ironic issues
a command to the agent to power off the machine from inside. This
feature avoids relying on often buggy soft power off features of BMCs
(especially IPMI-based), but is not compatible with the way FakeFish [1]
works in case of NC-SI hardware. Such hardware cannot be powered off
because doing so also removes network access to the BMC. FakeFish can
intercept any power calls but cannot intercept the agent API.
This OpenShift-only change adds a new annotation
baremetal.openshift.io/disable-agent-power-off which, if set to "true",
makes BMO configure the Ironic node with the "deploy_forces_oob_reboot"
DriverInfo flag. This flag prevents Ironic from issuing the in-band
power off request.
[1] …
=> [release-4.16] OCPBUGS-38938: [OCP] Ability to disable agent power off after deployment

controllers/metal3.io/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
At the end of a normal (not live ISO) deployment, Ironic issues
a command to the agent to power off the machine from inside. This
feature avoids relying on often buggy soft power off features of BMCs
(especially IPMI-based), but is not compatible with the way FakeFish [1]
works in case of NC-SI hardware. Such hardware cannot be powered off
because doing so also removes network access to the BMC. FakeFish can
intercept any power calls but cannot intercept the agent API.
This OpenShift-only change adds a new annotation
baremetal.openshift.io/disable-agent-power-off which, if set to "true",
makes BMO configure the Ironic node with the "deploy_forces_oob_reboot"
DriverInfo flag. This flag prevents Ironic from issuing the in-band
power off request.
[1] …
=> [release-4.15] OCPBUGS-38939: [OCP] Ability to disable agent power off after deployment

controllers/metal3.io/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
At the end of a normal (not live ISO) deployment, Ironic issues
a command to the agent to power off the machine from inside. This
feature avoids relying on often buggy soft power off features of BMCs
(especially IPMI-based), but is not compatible with the way FakeFish [1]
works in case of NC-SI hardware. Such hardware cannot be powered off
because doing so also removes network access to the BMC. FakeFish can
intercept any power calls but cannot intercept the agent API.
This OpenShift-only change adds a new annotation
baremetal.openshift.io/disable-agent-power-off which, if set to "true",
makes BMO configure the Ironic node with the "deploy_forces_oob_reboot"
DriverInfo flag. This flag prevents Ironic from issuing the in-band
power off request.
[1] …
=> [release-4.14] OCPBUGS-38940: [OCP] Ability to disable agent power off after deployment

controllers/metal3.io/baremetalhost_controller_test.go, controllers/metal3.io/host_config_data.go, controllers/metal3.io/host_config_data_test.go
The BareMetalHost CRD allows the UserData, MetaData, and NetworkData for the provisioned host to be specified as links to k8s Secrets. There are fields for both the Name and Namespace of the Secret, meaning that the baremetal-operator will read a Secret from any namespace. If a Secret contains the key "value" (or "userData", "metaData", or "networkData"), its corresponding value can be exfiltrated by a user provisioning a Host pointing to that Secret, then retrieving that data from the provisioned host.
Authored-by: Zane Bitter <zbitter@redhat.com>
Co-Authored-By: Dmitry Tantsur <dtantsur@protonmail.com>
Signed-off-by: Tuomo Tanskanen <tuomo.tanskanen@est.tech>
(cherry picked from commit 6b541a1d100e83a943d8ae50092149ad90f388b1)
=> OCPBUGS-39489: Disallow fetching secrets from namespaces different from the host's one

controllers/metal3.io/baremetalhost_controller_test.go, controllers/metal3.io/host_config_data.go, controllers/metal3.io/host_config_data_test.go
The BareMetalHost CRD allows the UserData, MetaData, and NetworkData for the provisioned host to be specified as links to k8s Secrets. There are fields for both the Name and Namespace of the Secret, meaning that the baremetal-operator will read a Secret from any namespace. If a Secret contains the key "value" (or "userData", "metaData", or "networkData"), its corresponding value can be exfiltrated by a user provisioning a Host pointing to that Secret, then retrieving that data from the provisioned host.
Authored-by: Zane Bitter <zbitter@redhat.com>
Co-Authored-By: Dmitry Tantsur <dtantsur@protonmail.com>
Signed-off-by: Tuomo Tanskanen <tuomo.tanskanen@est.tech>
(cherry picked from commit 6b541a1d100e83a943d8ae50092149ad90f388b1) (cherry picked from commit …
=> OCPBUGS-39490: Disallow fetching secrets from namespaces different from the host's one

controllers/metal3.io/baremetalhost_controller.go
Currently we are creating HFC for all BMH.
HFC only works for redfish based hardware, so we should only create when we detect that is redfish is in use.
=> [4.17] OCPBUGS-49701: Handle HFC for non-redfish HW

controllers/metal3.io/baremetalhost_controller.go
Currently we are creating HFC for all BMH.
HFC only works for redfish based hardware, so we should only create when we detect that is redfish is in use.
=> [4.16] OCPBUGS-49703: Handle HFC for non-redfish HW

go.mod, go.sum, vendor/golang.org/x/oauth2/LICENSE, vendor/golang.org/x/oauth2/README.md, vendor/golang.org/x/oauth2/oauth2.go, vendor/golang.org/x/oauth2/pkce.go, vendor/golang.org/x/oauth2/token.go, vendor/modules.txt
First we bumped golang to 1.23.0 since it's required for oauth2 0.27.0
Then we bumped the version
$ go get golang.org/x/oauth2@v0.27.0
$ go mod tidy
$ go mod vendor
=> [4.19] OCPBUGS-52215: Bump x/oauth2 to 0.27.0

apis/metal3.io/v1alpha1/bmceventsubscription_validation.go, apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go, controllers/metal3.io/bmceventsubscription_controller.go, controllers/metal3.io/bmceventsubscription_controller_test.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
Steps
$ git cherry-pick https://github.com/openshift/baremetal-operator/commit/84798044692b910263b1f50bf001814badec7ee5
$ make vendor
$ git add .
$ git commit # Vendorize
=> [4.17] OCPBUGS-53325: BMO can expose any secret via BMCEventSubscription CRD

apis/metal3.io/v1alpha1/bmceventsubscription_validation.go, apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go, controllers/metal3.io/bmceventsubscription_controller.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
Steps
$ git cherry-pick https://github.com/openshift/baremetal-operator/commit/84798044692b910263b1f50bf001814badec7ee5
$ make vendor
$ git add .
$ git commit # Vendorize
=> [4.15] OCPBUGS-53336: BMO can expose any secret via BMCEventSubscription CRD

apis/metal3.io/v1alpha1/bmceventsubscription_validation.go, apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go, controllers/metal3.io/bmceventsubscription_controller.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
Steps
$ git cherry-pick https://github.com/openshift/baremetal-operator/commit/84798044692b910263b1f50bf001814badec7ee5
$ make vendor
$ git add .
$ git commit # Vendorize
=> [4.14] OCPBUGS-53337: BMO can expose any secret via BMCEventSubscription CRD

apis/metal3.io/v1alpha1/bmceventsubscription_validation.go, apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go, controllers/metal3.io/bmceventsubscription_controller.go, controllers/metal3.io/bmceventsubscription_controller_test.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
The BMCEventSubscription spec uses a Secret reference for the HTTPHeadersRef field. This allows the user to specify any namespace. To prevent leaking Secrets, this commit restricts the namespace to the same namespace that the BMCEventSubscription is in.
Signed-off-by: Lennart Jern <lennart.jern@est.tech>
OCPBUGS-53334: CVE-2025-29781 ose-baremetal-operator-container: Bare Metal Operator (BMO) can expose any secret from other namespaces via BMCEventSubscription CRD [openshift-4.13.z]
Steps
$ git cherry-pick 8479804
$ make vendor
$ git add .
$ git commit # Vendorize
=> OCPBUGS-53334: BMO can expose any secret via BMCEventSubscription CRD 4.13

apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go, apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go, apis/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish_virtualmedia.go, pkg/hardwareutils/bmc/access_test.go, pkg/hardwareutils/bmc/idrac_virtualmedia.go, pkg/hardwareutils/bmc/redfish.go, pkg/hardwareutils/bmc/redfish_virtualmedia.go, test/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go, test/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go, test/vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish_virtualmedia.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac_virtualmedia.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish.go, vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/redfish_virtualmedia.go
Ironic supports [1] not providing a system ID when the BMC handles
exactly one system (which is a common case for standalone servers).
On the other hand, we see a high number of cases where the address is
provided as redfish://host/redfish/v1/, which currently fails with a
very confusing JSON parsing errors.
This change updates all Redfish drivers to ignore paths that are empty
or contain only /redfish/v1. Refactor the drivers to DRY.
[1] https://review.opendev.org/c/openstack/ironic/+/707208
Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>
(cherry picked from commit e70b7f5d9ca1d0826d9066b75ce8cb937d8843cf)
=> OCPBUGS-56026: Redfish: correctly handle missing system ID

apis/metal3.io/v1alpha1/baremetalhost_types.go, apis/metal3.io/v1alpha1/baremetalhost_types_test.go, config/default/ironic.env, config/overlays/e2e/ironic.env, config/render/capm3.yaml, internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation.go, internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation_test.go, pkg/provisioner/ironic/factory.go, pkg/provisioner/ironic/factory_test.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provision.go, pkg/provisioner/ironic/provision_test.go, test/vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
- **Provide an error when required checksum is missing**
- **Validate checksums at the webhook level**
- **Leave a TODO about OCI images**
- **Stop requiring DEPLOY_KERNEL/RAMDISK**
- **Remove DEPLOY_KERNEL_URL from deployment scripts for main**
- **Vendor update**
=> OCPBUGS-57472: merge from upstream

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/baremetalhost_controller_test.go
Cherry Pick from upstream commit metal3-io/baremetal-operator@0880ab00b9e2374528a5f4c0bc4be00de309de60
=> [4.19] OCPBUGS-56765: Make firmware update handle only a subset of `Spec.Updates`

controllers/metal3.io/dataimage_controller.go, controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go
When a host is in provisioned or externallyProvisioned state, has detached annotation and if a delete request is raised, it should directly move to deleting state.
(cherry picked from commit f2ccfecd10482f0a545c5fd14f61bd4ae920f5cf)
=> OCPBUGS-59133: Unblock BMH direct deletion when detached annotation is present
